# https://rust-lang.github.io/rustfmt/
array_width = 1
blank_lines_lower_bound = 1
blank_lines_upper_bound = 3
brace_style = "AlwaysNextLine"
color = "Always"
fn_params_layout = "Vertical"
fn_single_line = true
hard_tabs = true
imports_layout = "HorizontalVertical"
tab_spaces = 4
use_field_init_shorthand = true
use_try_shorthand = true
merge_derives = true
newline_style = "Unix"
match_block_trailing_comma = true